/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import modelo.BackgroundVO;
import modelo.ClasseVO;
import modelo.RacaVO;
import modelo.SubClasseVO;
import modelo.SubRacaVO;
import modelo.UsuarioVO;

/**
 *
 * @author 181700271
 */
public class GUICriarPersonagem extends javax.swing.JInternalFrame
{
    UsuarioVO usuarioLogado;
    
    /**
     * Creates new form GUICriarPersonagem
     * @param usuarioLogado
     */
    public GUICriarPersonagem(UsuarioVO usuarioLogado) {
        initComponents();
        this.usuarioLogado = usuarioLogado;
    }
    
    private BackgroundVO carregarBackgrounds()
    {
        
    }
    private ClasseVO carregarClasses()
    {
        
    }
    private RacaVO carregarRacas()
    {
        
    }
    private SubClasseVO carregarSubclasses(ClasseVO classe)
    {
        
    }
    private SubRacaVO carregarSubracas(RacaVO raca)
    {
        
    }
    
    private void criarPersonagem()
    {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelClasse = new javax.swing.JPanel();
        jPanelRaca = new javax.swing.JPanel();
        jPanelBackground = new javax.swing.JPanel();
        jPanelBackstory = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanelClasseLayout = new javax.swing.GroupLayout(jPanelClasse);
        jPanelClasse.setLayout(jPanelClasseLayout);
        jPanelClasseLayout.setHorizontalGroup(
            jPanelClasseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 735, Short.MAX_VALUE)
        );
        jPanelClasseLayout.setVerticalGroup(
            jPanelClasseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Classe", jPanelClasse);

        javax.swing.GroupLayout jPanelRacaLayout = new javax.swing.GroupLayout(jPanelRaca);
        jPanelRaca.setLayout(jPanelRacaLayout);
        jPanelRacaLayout.setHorizontalGroup(
            jPanelRacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 735, Short.MAX_VALUE)
        );
        jPanelRacaLayout.setVerticalGroup(
            jPanelRacaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Raça", jPanelRaca);

        javax.swing.GroupLayout jPanelBackgroundLayout = new javax.swing.GroupLayout(jPanelBackground);
        jPanelBackground.setLayout(jPanelBackgroundLayout);
        jPanelBackgroundLayout.setHorizontalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 735, Short.MAX_VALUE)
        );
        jPanelBackgroundLayout.setVerticalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Background", jPanelBackground);

        javax.swing.GroupLayout jPanelBackstoryLayout = new javax.swing.GroupLayout(jPanelBackstory);
        jPanelBackstory.setLayout(jPanelBackstoryLayout);
        jPanelBackstoryLayout.setHorizontalGroup(
            jPanelBackstoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 735, Short.MAX_VALUE)
        );
        jPanelBackstoryLayout.setVerticalGroup(
            jPanelBackstoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Backstory", jPanelBackstory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JPanel jPanelBackstory;
    private javax.swing.JPanel jPanelClasse;
    private javax.swing.JPanel jPanelRaca;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
