/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

import exception.NoUserFoundException;
import exception.WrongArgumentTypeException;
import modelo.LoginVO;
import modelo.UsuarioVO;
import servicos.ServicosFactory;

/**
 *
 * @author 181700271
 */
public class GUILogin extends javax.swing.JInternalFrame {
    
    private UsuarioVO usuarioVOLogado;
    
    /**
     * Creates new form GUILogin
     */
    public GUILogin() {
        initComponents();
        usuarioVOLogado = null;
    }
    
    public GUILogin(String usuario) {
        initComponents();
        jtfUsuarioLogin.setText(usuario);
        usuarioVOLogado = null;
    }
    
    private void limparTexto()
    {
        jtfUsuarioLogin.setText(null);
        jpfSenhaLogin.setText(null);
    }
    
    private void login()
    {
        LoginVO lVO = new LoginVO();
        lVO.setUsuario(jtfUsuarioLogin.getText());
        lVO.setSenha(new String(jpfSenhaLogin.getPassword()));
        limparTexto();
        
        try
        {
            UsuarioVO uVO = ServicosFactory.getUsuarioServicos().loginUsuario(lVO);
            
            if(uVO == null)
                JOptionPane.showMessageDialog(null, "Usuário e/ou Senha inválidos!");
            else
            {
                uVO.setSenha("Senha");
                usuarioVOLogado = uVO;
                dispose();
            }
        }
        catch(SQLException se) {
            JOptionPane.showMessageDialog(null, se.getMessage(), "Erro: ", JOptionPane.ERROR_MESSAGE);
        }
        catch(NoUserFoundException nufe) {
            JOptionPane.showMessageDialog(null, nufe.getMessage(), "Aviso: ", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void cadastrar()
    {
        UsuarioVO uVO = new UsuarioVO();
        //buildar usuário
        limparTexto();
        
        try
        {
            ServicosFactory.getUsuarioServicos().cadastrarUsuario(uVO);
            uVO.setSenha("Senha");
            usuarioVOLogado = uVO;
            dispose();
        }
        catch(SQLException se) {
            JOptionPane.showMessageDialog(null, se.getMessage(), "Erro: ", JOptionPane.ERROR_MESSAGE);
        }
        catch(WrongArgumentTypeException wate) {
            JOptionPane.showMessageDialog(null, wate.getMessage(), "Erro: ", JOptionPane.WARNING_MESSAGE);
        }
    }
    
    private void sair()
    {
        limparTexto();
        dispose();
    }

    public UsuarioVO getUsuarioVOLogado() {
        return usuarioVOLogado;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jPanelLogin = new javax.swing.JPanel();
        jPanelDadosLogin = new javax.swing.JPanel();
        jlblUsuarioLogin = new javax.swing.JLabel();
        jtfUsuarioLogin = new javax.swing.JTextField();
        jlblSenhaLogin = new javax.swing.JLabel();
        jpfSenhaLogin = new javax.swing.JPasswordField();
        jPanelBotoesLogin = new javax.swing.JPanel();
        jbtnLogin = new javax.swing.JButton();
        jbtnCadastrar = new javax.swing.JButton();
        jbtnSair = new javax.swing.JButton();
        jPanelCadastro = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setTitle("Login");
        setToolTipText("Login");

        jPanelDadosLogin.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados"));
        jPanelDadosLogin.setToolTipText("");
        jPanelDadosLogin.setName(""); // NOI18N

        jlblUsuarioLogin.setText("Usuário:");

        jlblSenhaLogin.setText("Senha:");

        javax.swing.GroupLayout jPanelDadosLoginLayout = new javax.swing.GroupLayout(jPanelDadosLogin);
        jPanelDadosLogin.setLayout(jPanelDadosLoginLayout);
        jPanelDadosLoginLayout.setHorizontalGroup(
            jPanelDadosLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblSenhaLogin)
                    .addComponent(jlblUsuarioLogin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelDadosLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfUsuarioLogin)
                    .addComponent(jpfSenhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanelDadosLoginLayout.setVerticalGroup(
            jPanelDadosLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblUsuarioLogin)
                    .addComponent(jtfUsuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelDadosLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblSenhaLogin)
                    .addComponent(jpfSenhaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelBotoesLogin.setBorder(javax.swing.BorderFactory.createTitledBorder("Ações"));

        jbtnLogin.setText("Login");
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });
        jbtnLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnLoginKeyPressed(evt);
            }
        });

        jbtnCadastrar.setText("Cadastrar");
        jbtnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCadastrarActionPerformed(evt);
            }
        });
        jbtnCadastrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnCadastrarKeyPressed(evt);
            }
        });

        jbtnSair.setText("Sair");
        jbtnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSairActionPerformed(evt);
            }
        });
        jbtnSair.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnSairKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBotoesLoginLayout = new javax.swing.GroupLayout(jPanelBotoesLogin);
        jPanelBotoesLogin.setLayout(jPanelBotoesLoginLayout);
        jPanelBotoesLoginLayout.setHorizontalGroup(
            jPanelBotoesLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbtnLogin)
                .addGap(18, 18, 18)
                .addComponent(jbtnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jbtnSair)
                .addContainerGap())
        );
        jPanelBotoesLoginLayout.setVerticalGroup(
            jPanelBotoesLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBotoesLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBotoesLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnLogin)
                    .addComponent(jbtnSair)
                    .addComponent(jbtnCadastrar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelLoginLayout = new javax.swing.GroupLayout(jPanelLogin);
        jPanelLogin.setLayout(jPanelLoginLayout);
        jPanelLoginLayout.setHorizontalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDadosLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBotoesLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelLoginLayout.setVerticalGroup(
            jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelDadosLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelBotoesLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Login", jPanelLogin);

        javax.swing.GroupLayout jPanelCadastroLayout = new javax.swing.GroupLayout(jPanelCadastro);
        jPanelCadastro.setLayout(jPanelCadastroLayout);
        jPanelCadastroLayout.setHorizontalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );
        jPanelCadastroLayout.setVerticalGroup(
            jPanelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Cadastro", jPanelCadastro);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        login();
    }//GEN-LAST:event_jbtnLoginActionPerformed

    private void jbtnLoginKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnLoginKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            login();
    }//GEN-LAST:event_jbtnLoginKeyPressed

    private void jbtnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCadastrarActionPerformed
        cadastrar();
    }//GEN-LAST:event_jbtnCadastrarActionPerformed

    private void jbtnCadastrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnCadastrarKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            cadastrar();
    }//GEN-LAST:event_jbtnCadastrarKeyPressed

    private void jbtnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSairActionPerformed
        sair();
    }//GEN-LAST:event_jbtnSairActionPerformed

    private void jbtnSairKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnSairKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            sair();
    }//GEN-LAST:event_jbtnSairKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelBotoesLogin;
    private javax.swing.JPanel jPanelCadastro;
    private javax.swing.JPanel jPanelDadosLogin;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JButton jbtnCadastrar;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JButton jbtnSair;
    private javax.swing.JLabel jlblSenhaLogin;
    private javax.swing.JLabel jlblUsuarioLogin;
    private javax.swing.JPasswordField jpfSenhaLogin;
    private javax.swing.JTextField jtfUsuarioLogin;
    // End of variables declaration//GEN-END:variables
}
