/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.SQLException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;

import exception.NoDataFoundException;
import modelo.ImagemVO;
import modelo.UsuarioVO;
import servicos.ServicosFactory;

/**
 *
 * @author Eduardo Pereira Moreira
 */
public class GUIPrincipal extends javax.swing.JFrame implements InternalFrameListener{

    private UsuarioVO usuarioVOLogado;
    private ImagemVO[] imagemUsuarioVOLogado;
    
    private boolean flagGUIPersonagens = false;
    private boolean flagGUIFichas = false;
    
    private GUIPrincipal() {
        System.exit(0);
    }
    /**
     * Creates new form GUIPrincipal
     * @param usuarioVOLogado
     */
    public GUIPrincipal(UsuarioVO usuarioVOLogado) {
        initComponents();
        this.usuarioVOLogado = usuarioVOLogado;
        preencherPerfil();
    }
    
    private void preencherPerfil(){
        try
        {
            String dadoPesquisa = Integer.toString(usuarioVOLogado.getIdImagem());
            imagemUsuarioVOLogado = ServicosFactory.getImagemServicos().pesquisarImagemUsuario(1, dadoPesquisa);
            
            BufferedImage imagemUsuario = ImageIO.read(
                    getClass().getResource(imagemUsuarioVOLogado[0].getCaminhoImagem())
            );
            
            jLabelImagem.setIcon(new ImageIcon(imagemUsuario));
            jLabelNomeUsuario.setText(usuarioVOLogado.getNome());
        }
        catch (SQLException | NoDataFoundException | IOException ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void limparPerfil(){
        usuarioVOLogado = null;
        imagemUsuarioVOLogado = null;
        jLabelImagem.setIcon(null);
        jLabelNomeUsuario.setText(null);
    }
    
    private void abrirGUIPersonagens(){ 
        if(!flagGUIPersonagens){
            GUIPersonagens guiP = new GUIPersonagens(usuarioVOLogado.getId());
            jdpPrincipal.add(guiP);
            guiP.setVisible(true);
            flagGUIPersonagens = true;
            guiP.addInternalFrameListener(this);
        }
    }
    private void abrirGUIFichas(){
        if(!flagGUIFichas){
            GUIFichas guiF = new GUIFichas(usuarioVOLogado.getId());
            jdpPrincipal.add(guiF);
            guiF.setVisible(true);
            flagGUIFichas = true;
            guiF.addInternalFrameListener(this);
        }
    }
    
    private void logoff(){
        limparPerfil();
        
        GUILogin guiL = new GUILogin();
        guiL.setVisible(true);
        
        setVisible(false);
        dispose();
    }
    
    private void encerrar(){
        limparPerfil();
        System.exit(0);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPerfil = new javax.swing.JPanel();
        jLabelImagem = new javax.swing.JLabel();
        jLabelNomeUsuario = new javax.swing.JLabel();
        jdpPrincipal = new javax.swing.JDesktopPane();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuPersonagens = new javax.swing.JMenu();
        jmiPersonagens = new javax.swing.JMenuItem();
        jmiFichas = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jmiLogoff = new javax.swing.JMenuItem();
        jmiEncerrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        jPanelPerfil.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelImagem.setText("Imagem Usuário");

        jLabelNomeUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNomeUsuario.setText("Nome do Usuário");

        javax.swing.GroupLayout jPanelPerfilLayout = new javax.swing.GroupLayout(jPanelPerfil);
        jPanelPerfil.setLayout(jPanelPerfilLayout);
        jPanelPerfilLayout.setHorizontalGroup(
            jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(231, 231, 231)
                .addComponent(jLabelNomeUsuario)
                .addContainerGap(314, Short.MAX_VALUE))
        );
        jPanelPerfilLayout.setVerticalGroup(
            jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPerfilLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabelNomeUsuario)
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jdpPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jdpPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 784, Short.MAX_VALUE)
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );

        jMenuPersonagens.setText("Personagens");

        jmiPersonagens.setText("Criar/Editar Personagem");
        jmiPersonagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPersonagensActionPerformed(evt);
            }
        });
        jmiPersonagens.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmiPersonagensKeyPressed(evt);
            }
        });
        jMenuPersonagens.add(jmiPersonagens);

        jmiFichas.setText("Fichas dos Personagens");
        jmiFichas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFichasActionPerformed(evt);
            }
        });
        jmiFichas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmiFichasKeyPressed(evt);
            }
        });
        jMenuPersonagens.add(jmiFichas);

        jMenuBar.add(jMenuPersonagens);

        jMenuSair.setText("Sair");

        jmiLogoff.setText("Fazer Logoff");
        jmiLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLogoffActionPerformed(evt);
            }
        });
        jmiLogoff.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmiLogoffKeyPressed(evt);
            }
        });
        jMenuSair.add(jmiLogoff);

        jmiEncerrar.setText("Encerrar o Programa");
        jmiEncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEncerrarActionPerformed(evt);
            }
        });
        jmiEncerrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmiEncerrarKeyPressed(evt);
            }
        });
        jMenuSair.add(jmiEncerrar);

        jMenuBar.add(jMenuSair);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdpPrincipal)
                    .addComponent(jPanelPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jdpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLogoffActionPerformed
        logoff();
    }//GEN-LAST:event_jmiLogoffActionPerformed

    private void jmiLogoffKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmiLogoffKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            logoff();
        }
    }//GEN-LAST:event_jmiLogoffKeyPressed

    private void jmiEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEncerrarActionPerformed
        encerrar();
    }//GEN-LAST:event_jmiEncerrarActionPerformed

    private void jmiEncerrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmiEncerrarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            encerrar();
        }
    }//GEN-LAST:event_jmiEncerrarKeyPressed

    private void jmiPersonagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPersonagensActionPerformed
        abrirGUIPersonagens();
    }//GEN-LAST:event_jmiPersonagensActionPerformed

    private void jmiPersonagensKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmiPersonagensKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            abrirGUIPersonagens();
        }
    }//GEN-LAST:event_jmiPersonagensKeyPressed

    private void jmiFichasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFichasActionPerformed
        abrirGUIFichas();
    }//GEN-LAST:event_jmiFichasActionPerformed

    private void jmiFichasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmiFichasKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            abrirGUIFichas();
        }
    }//GEN-LAST:event_jmiFichasKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JLabel jLabelNomeUsuario;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuPersonagens;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelPerfil;
    private javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JMenuItem jmiEncerrar;
    private javax.swing.JMenuItem jmiFichas;
    private javax.swing.JMenuItem jmiLogoff;
    private javax.swing.JMenuItem jmiPersonagens;
    // End of variables declaration//GEN-END:variables

    @Override
    public void internalFrameOpened(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameClosing(InternalFrameEvent ife) {

    }

    @Override
    public void internalFrameClosed(InternalFrameEvent ife) {
        JInternalFrame iFrame = ife.getInternalFrame();
        if(iFrame instanceof GUIPersonagens) {
            flagGUIPersonagens = false;
        }
        else if(iFrame instanceof GUIFichas) {
            flagGUIFichas = false;
        }
    }

    @Override
    public void internalFrameIconified(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameDeiconified(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameActivated(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameDeactivated(InternalFrameEvent ife) {
        
    }
}
