/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import com.sun.glass.events.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;
import modelo.UsuarioVO;

/**
 *
 * @author 181700271
 */
public class GUIPrincipal extends javax.swing.JFrame implements InternalFrameListener{

    private UsuarioVO usuarioVOLogado;
    private boolean flagGUILogin = false;
    private boolean flagGUIPersonagens = false;
    /**
     * Creates new form GUIPrincipal
     */
    public GUIPrincipal() {
        initComponents();
        login();
    }
    
    private void login()
    {
        if(!flagGUILogin)
        {
            GUILogin gl = new GUILogin();
            jdpPrincipal.add(gl);
            gl.setVisible(true);
            flagGUILogin = true;
            gl.addInternalFrameListener(this);
        }
    }
    
    private void preencherPerfil()
    {
        try{
            BufferedImage imagemUsuario = ImageIO.read(getClass().getResource(usuarioVOLogado.getImagem().getCaminhoImagem()));
            jLabelImagem.setIcon(new ImageIcon(imagemUsuario));
            jLabelNomeUsuario.setText(usuarioVOLogado.getNome());
        }
        catch(IOException IOe){
            
        }
    }
    
    private void limparPerfil()
    {
        
    }
    
    private void personagens()
    {
        if(!flagGUIPersonagens)
        {
            GUIPersonagens gp = new GUIPersonagens();
            jdpPrincipal.add(gp);
            gp.setVisible(true);
            flagGUIPersonagens = true;
            gp.addInternalFrameListener(this);
        }
    }
    
    private void logoff()
    {
        usuarioVOLogado = null;
        limparPerfil();
        login();
    }
    
    private void encerrar()
    {
        System.exit(0);
    }
    


    public UsuarioVO getUsuarioVOLogado() {
        return usuarioVOLogado;
    }
    public void setUsuarioVOLogado(UsuarioVO usuarioVOLogado) {
        this.usuarioVOLogado = usuarioVOLogado;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPerfil = new javax.swing.JPanel();
        jLabelImagem = new javax.swing.JLabel();
        jLabelNomeUsuario = new javax.swing.JLabel();
        jdpPrincipal = new javax.swing.JDesktopPane();
        jMenuBar = new javax.swing.JMenuBar();
        jMenuPersonagens = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();
        jmiLogoff = new javax.swing.JMenuItem();
        jmiEncerrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));

        jPanelPerfil.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelNomeUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNomeUsuario.setText("Nome do Usuário");

        javax.swing.GroupLayout jPanelPerfilLayout = new javax.swing.GroupLayout(jPanelPerfil);
        jPanelPerfil.setLayout(jPanelPerfilLayout);
        jPanelPerfilLayout.setHorizontalGroup(
            jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPerfilLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(241, 241, 241)
                .addComponent(jLabelNomeUsuario)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPerfilLayout.setVerticalGroup(
            jPanelPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPerfilLayout.createSequentialGroup()
                .addContainerGap(44, Short.MAX_VALUE)
                .addComponent(jLabelNomeUsuario)
                .addGap(42, 42, 42))
            .addGroup(jPanelPerfilLayout.createSequentialGroup()
                .addComponent(jLabelImagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jdpPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        jdpPrincipal.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 784, Short.MAX_VALUE)
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );

        jMenuPersonagens.setText("Personagens");
        jMenuPersonagens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuPersonagensActionPerformed(evt);
            }
        });
        jMenuPersonagens.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jMenuPersonagensKeyPressed(evt);
            }
        });
        jMenuBar.add(jMenuPersonagens);

        jMenuSair.setText("Sair");

        jmiLogoff.setText("Fazer Logoff");
        jmiLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiLogoffActionPerformed(evt);
            }
        });
        jmiLogoff.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmiLogoffKeyPressed(evt);
            }
        });
        jMenuSair.add(jmiLogoff);

        jmiEncerrar.setText("Encerrar o Programa");
        jmiEncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiEncerrarActionPerformed(evt);
            }
        });
        jmiEncerrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jmiEncerrarKeyPressed(evt);
            }
        });
        jMenuSair.add(jmiEncerrar);

        jMenuBar.add(jMenuSair);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jdpPrincipal)
                    .addComponent(jPanelPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jdpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuPersonagensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuPersonagensActionPerformed
        personagens();
    }//GEN-LAST:event_jMenuPersonagensActionPerformed

    private void jMenuPersonagensKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jMenuPersonagensKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            personagens();
        }
    }//GEN-LAST:event_jMenuPersonagensKeyPressed

    private void jmiLogoffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiLogoffActionPerformed
        logoff();
    }//GEN-LAST:event_jmiLogoffActionPerformed

    private void jmiLogoffKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmiLogoffKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            logoff();
        }
    }//GEN-LAST:event_jmiLogoffKeyPressed

    private void jmiEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiEncerrarActionPerformed
        encerrar();
    }//GEN-LAST:event_jmiEncerrarActionPerformed

    private void jmiEncerrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jmiEncerrarKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            encerrar();
        }
    }//GEN-LAST:event_jmiEncerrarKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JLabel jLabelNomeUsuario;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenu jMenuPersonagens;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelPerfil;
    private javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JMenuItem jmiEncerrar;
    private javax.swing.JMenuItem jmiLogoff;
    // End of variables declaration//GEN-END:variables

    @Override
    public void internalFrameOpened(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameClosing(InternalFrameEvent ife) {
        JInternalFrame iFrame = ife.getInternalFrame();
        if(iFrame instanceof GUILogin)
            usuarioVOLogado = ((GUILogin) iFrame).getUsuarioVOLogado();
    }

    @Override
    public void internalFrameClosed(InternalFrameEvent ife) {
        JInternalFrame iFrame = ife.getInternalFrame();
        if(iFrame instanceof GUILogin) {
                flagGUILogin = false;
                preencherPerfil();
        }
        else if(iFrame instanceof GUIPersonagens) {
            flagGUIPersonagens = false;
        }
    }

    @Override
    public void internalFrameIconified(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameDeiconified(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameActivated(InternalFrameEvent ife) {
        
    }

    @Override
    public void internalFrameDeactivated(InternalFrameEvent ife) {
        
    }
}
